apiVersion: batch/v1
kind: CronJob
metadata:
  name: check-fluentbit-logs  # Nome do CronJob
spec:
  schedule: "*/5 * * * *"  # Define que o CronJob será executado a cada 5 minutos
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: log-checker
            image: bitnami/aws-cli  # Usa uma imagem que já vem com kubectl e AWS CLI pré-instalados
            command:
            - /bin/sh
            - -c
            - |
              echo "🔍 Verificando logs no S3 do LocalStack..."

              # Define credenciais falsas para acessar o LocalStack via AWS CLI
              export AWS_ACCESS_KEY_ID=test
              export AWS_SECRET_ACCESS_KEY=test
              export AWS_DEFAULT_REGION=us-east-1

              # Configurações do LocalStack e do Fluent Bit
              ENDPOINT="http://host.docker.internal:4566"  # Endereço do LocalStack no Docker Desktop
              BUCKET="log-bucket"  # Nome do bucket onde os logs são armazenados
              FLUENTBIT_LABEL="app=fluent-bit"  # Rótulo (label) do Fluent Bit para reiniciar caso necessário

              # Obtém o timestamp do último log armazenado no bucket do S3
              LAST_LOG_TIME=$(aws --endpoint-url=$ENDPOINT s3 ls s3://$BUCKET/ --recursive | awk '{print $1, $2}' | sort | tail -n 1)

              # Verifica se há logs recentes no bucket
              if [ -z "$LAST_LOG_TIME" ]; then
                  echo "🚨 Nenhum log encontrado no bucket! Reiniciando Fluent Bit..."
                  kubectl rollout restart deployment -l $FLUENTBIT_LABEL  # Reinicia o deployment do Fluent Bit
              else
                  echo "✅ Último log encontrado em: $LAST_LOG_TIME"
              fi

            # Define variáveis de ambiente dentro do container (mesmo que já sejam configuradas no script)
            env:
              - name: AWS_ACCESS_KEY_ID
                value: "test"
              - name: AWS_SECRET_ACCESS_KEY
                value: "test"
              - name: AWS_DEFAULT_REGION
                value: "us-east-1"
                
          restartPolicy: OnFailure  # Caso o job falhe, ele será reiniciado automaticamente
          serviceAccountName: fluentbit-check-sa  # Conta de serviço que permite que o job execute comandos no cluster Kubernetes
