apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Parsers_File  parsers.conf

    [INPUT]
        Name          tail
        Path          /var/log/containers/log-generator-*.log
        Tag          kube.*
        Parser       docker
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [FILTER]
        Name          kubernetes
        Match         kube.*
        Kube_URL      https://kubernetes.default.svc:443
        Merge_Log     On
        Keep_Log      Off

    [FILTER]
        Name          modify
        Match         kube.*
        Remove        stream

    [OUTPUT]
        Name              s3
        Match             *
        Bucket            log-bucket
        Region            us-east-1
        Endpoint          http://host.docker.internal:4566
        Storage_Class     STANDARD
        Auto_Retry_Requests On
        Use_Put_Object    On
        Content_Type      application/json
        S3_Key_Format     /logs/%Y/%m/%d/log-$UUID.log
        Compression       gzip

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
