apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit-check-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fluentbit-check-role
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "update", "patch"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fluentbit-check-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: fluentbit-check-sa
    namespace: default
roleRef:
  kind: Role
  name: fluentbit-check-role
  apiGroup: rbac.authorization.k8s.io
